name: JMeter Test Pipeline

on:
  push:
    paths:
      - 'http_request/**'
      - 'config_element/**'
      - 'summary_report/**'
      - 'view_results/**'
      - 'commonUsedElement/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      http_request: ${{ steps.filter.outputs.http_request }}
      config_element: ${{ steps.filter.outputs.config_element }}
      summary_report: ${{ steps.filter.outputs.summary_report }}
      view_results: ${{ steps.filter.outputs.view_results }}
      commonUsedElement: ${{ steps.filter.outputs.commonUsedElement }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            http_request: http_request/**
            config_element: config_element/**
            summary_report: summary_report/**
            view_results: view_results/**
            commonUsedElement: commonUsedElement/**

  http_request_tests:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.http_request == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 jmeter

      - name: Run JMeter Tests
        run: |
          for file in http_request/*.jmx; do
            if [ -f "$file" ]; then
              ./jmeter/bin/jmeter -n -t "$file" -l "results/$(basename "$file" .jmx).jtl" -e -o "results/$(basename "$file" .jmx)"
            fi
          done
        continue-on-error: true

      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        with:
          name: http_request_test_results
          path: results/

  config_element_tests:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.config_element == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 jmeter

      - name: Run JMeter Tests
        run: |
          for file in config_element/*.jmx; do
            if [ -f "$file" ]; then
              ./jmeter/bin/jmeter -n -t "$file" -l "results/$(basename "$file" .jmx).jtl" -e -o "results/$(basename "$file" .jmx)"
            fi
          done
        continue-on-error: true

      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        with:
          name: config_element_test_results
          path: results/

  summary_report_tests:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.summary_report == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 jmeter

      - name: Run JMeter Tests
        run: |
          for file in summary_report/*.jmx; do
            if [ -f "$file" ]; then
              ./jmeter/bin/jmeter -n -t "$file" -l "results/$(basename "$file" .jmx).jtl" -e -o "results/$(basename "$file" .jmx)"
            fi
          done
        continue-on-error: true

      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        with:
          name: summary_report_test_results
          path: results/

  view_results_tests:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.view_results == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 jmeter

      - name: Run JMeter Tests
        run: |
          for file in view_results/*.jmx; do
            if [ -f "$file" ]; then
              ./jmeter/bin/jmeter -n -t "$file" -l "results/$(basename "$file" .jmx).jtl" -e -o "results/$(basename "$file" .jmx)"
            fi
          done
        continue-on-error: true

      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        with:
          name: view_results_test_results
          path: results/

  commonUsedElement_tests:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.commonUsedElement == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 jmeter

      - name: Run JMeter Tests
        run: |
          for file in commonUsedElement/*.jmx; do
            if [ -f "$file" ]; then
              ./jmeter/bin/jmeter -n -t "$file" -l "results/$(basename "$file" .jmx).jtl" -e -o "results/$(basename "$file" .jmx)"
            fi
          done
        continue-on-error: true

      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        with:
          name: commonUsedElement_test_results
          path: results/